spring:
  data:
    mongodb:
      uri: mongodb+srv://juancaraballo:yabH3MR5aVjRESF0@cluster0.yeqdoqp.mongodb.net/
      database: hoteles

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
