spring:
  data:
    mongodb:
      uri: mongodb://ISIS2304B01202320:WYCSTxdMGKyr@157.253.236.88:8087/ISIS2304B01202320
      database: Sistrans

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
